event:
    path:     /
    defaults: { _controller: "EventBundle:Event:index" }

event_show:
    path:     /{slug}/show
    defaults: { _controller: "EventBundle:Event:show" }

event_new:
    path:     /new
    defaults: { _controller: "EventBundle:Event:new" }

event_create:
    path:     /create
    defaults: { _controller: "EventBundle:Event:create" }
    requirements: { _method: post }

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }

event_update:
    path:     /{id}/update
    defaults: { _controller: "EventBundle:Event:update" }
    requirements: { _method: post|put }

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    requirements: { _method: post|delete }


event_attend:
    path:     /{id}/attend.{format}
    defaults: { _controller: "EventBundle:Event:attend", format:html }

event_unattend:
    path:     /{id}/unattend
    defaults: { _controller: "EventBundle:Event:unattend" }