<?php

namespace Yoda\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param string $username
     * @return User|null
     */
    public function findOneByUsernameOrEmail($username)
    {

        return $this->createQueryBuilder('u')
            ->andWhere('u.username = :username or u.email = :username')
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult();

    }
}
