services:
#    event.example:
#        class: Yoda\EventBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    report_event_manager:
        class: Yoda\EventBundle\Reporting\EventReportManager
        arguments: [@doctrine.orm.entity_manager]